# Generated by Django 4.1.2 on 2022-10-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField()),
                ('page_title', models.CharField(max_length=30)),
                ('page_name', models.CharField(max_length=20)),
                ('page_external_links', models.CharField(max_length=1000)),
                ('page_overview', models.TextField(max_length=350)),
                ('page_body_text', models.TextField(max_length=5000)),
            ],
        ),
    ]
