# Generated by Django 4.1.2 on 2022-10-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_external_links',
        ),
    ]
