# Generated by Django 4.1.2 on 2022-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcport', '0002_remove_page_page_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_nav_list',
            field=models.TextField(default=['Intro', 'Work', 'About', 'Contact'], max_length=150),
        ),
    ]
