# Generated by Django 4.1.2 on 2022-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcport', '0003_page_page_nav_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_nav_list',
            field=models.TextField(default='Intro, Work, About, Contact', max_length=150),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(max_length=50),
        ),
    ]
