# Generated by Django 4.1.2 on 2022-10-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcport', '0004_alter_page_page_name_alter_page_page_nav_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
