# Generated by Django 4.1.2 on 2022-10-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcport', '0005_page_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_nav_list',
        ),
    ]
